_format_version: "2.1"

services:
  - name: auth
    url: http://auth:9999
    routes:
      - name: auth
        paths: ["/auth/v1"]
        strip_path: true
        protocols: ["http", "https"]

  - name: rest
    url: http://rest:3000
    routes:
      - name: rest
        paths: ["/rest/v1"]
        strip_path: true
        protocols: ["http", "https"]

  - name: realtime
    url: http://realtime:4000
    routes:
      - name: realtime-ws
        paths: ["/realtime/v1"]
        strip_path: true
        protocols: ["http", "https"]

plugins:
  - name: cors
    config:
      origins: ["*"]
      methods: ["GET","POST","PUT","PATCH","DELETE","OPTIONS"]
      headers: ["Authorization","apikey","x-client-info","content-type"]
      exposed_headers: ["content-type"]
      credentials: true
      max_age: 3600

  - name: key-auth
    config:
      key_names: ["apikey"]
      hide_credentials: false

consumers:
  - username: anon
    keyauth_credentials:
      - key: ${SUPABASE_ANON_KEY}
  - username: service_role
    keyauth_credentials:
      - key: ${SUPABASE_SERVICE_KEY}
